In [1]:
import pandas as pd

import numpy as np

from sklearn.metrics import classification_report

from sklearn.datasets import load_breast_cancer

from sklearn.ensemble import GradientBoostingClassifier

from sklearn.model_selection import train_test_split

In [2]:
df = pd.DataFrame(load_breast_cancer()['data'],

columns=load_breast_cancer()['feature_names'])

df['y'] = load_breast_cancer()['target']

df.head(5)

   mean radius  mean texture  ...  worst fractal dimension  y
0        17.99         10.38  ...                  0.11890  0
1        20.57         17.77  ...                  0.08902  0
2        19.69         21.25  ...                  0.08758  0
3        11.42         20.38  ...                  0.17300  0
4        20.29         14.34  ...                  0.07678  0

[5 rows x 31 columns]

In [4]:
X,y = df.drop('y',axis=1),df.y

test_size = 0.30 # taking 70:30 training and test set

seed = 7  # Random number seeding for reapeatability of the code

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)

gradient_booster = GradientBoostingClassifier(learning_rate=0.1)

gradient_booster.fit(X_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [6]:
print(classification_report(y,gradient_booster.predict(X)))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       212
           1       0.99      1.00      1.00       357

    accuracy                           0.99       569
   macro avg       0.99      0.99      0.99       569
weighted avg       0.99      0.99      0.99       569